# Generated by Django 2.2.4 on 2020-08-23 19:05

from django.db import migrations

def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            owner_phone=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure
            )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Flat')
    Owner.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners)
    ]
