# Generated by Django 2.2.4 on 2020-08-25 22:03

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            owner_phone=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure)

        owner.flats.set([flat])
        owner.save()


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200823_2205'),
    ]

    operations = [
        migrations.RunPython(fill_owners),
    ]
